module.exports = class Data1701679557854 {
    name = 'Data1701679557854'

    async up(db) {
        await db.query(`CREATE TABLE "lido_config" ("id" character varying NOT NULL, "insurance_fund" text, "oracle" text, "treasury" text, "is_stopped" boolean NOT NULL, "is_staking_paused" boolean NOT NULL, "max_stake_limit" numeric NOT NULL, "stake_limit_increase_per_block" numeric NOT NULL, "el_rewards_vault" text, "el_rewards_withdrawal_limit_points" numeric NOT NULL, "withdrawal_credentials" text NOT NULL, "wc_set_by" text, "lido_locator" text, CONSTRAINT "PK_616d6a5f5d35ea7b294d1d21f5a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "lido_transfer" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "value" numeric NOT NULL, "shares" numeric NOT NULL, "shares_before_decrease" numeric, "shares_after_decrease" numeric, "shares_before_increase" numeric, "shares_after_increase" numeric, "total_pooled_ether" numeric NOT NULL, "total_shares" numeric NOT NULL, "balance_after_decrease" numeric, "balance_after_increase" numeric, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "transaction_index" numeric NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_9a64be305b41f2dfe3391b96044" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "lido_approval" ("id" character varying NOT NULL, "owner" text NOT NULL, "spender" text NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_08e54ad94d6befca3940de1bd7e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "lido_submission" ("id" character varying NOT NULL, "sender" text NOT NULL, "amount" numeric NOT NULL, "referral" text NOT NULL, "shares" numeric NOT NULL, "shares_before" numeric NOT NULL, "shares_after" numeric NOT NULL, "total_pooled_ether_before" numeric NOT NULL, "total_pooled_ether_after" numeric NOT NULL, "total_shares_before" numeric NOT NULL, "total_shares_after" numeric NOT NULL, "balance_after" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "transaction_index" numeric NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_d128862f38cf4e008fb0987372d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "node_operators_shares" ("id" character varying NOT NULL, "address" text NOT NULL, "shares" numeric NOT NULL, "total_reward_id" character varying, CONSTRAINT "PK_5ed87e57834752491eb01a3a1d8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d7de92f3dc4d98a1cd3fd1092e" ON "node_operators_shares" ("total_reward_id") `)
        await db.query(`CREATE TABLE "total_reward" ("id" character varying NOT NULL, "total_rewards" numeric NOT NULL, "total_rewards_with_fees" numeric NOT NULL, "mev_fee" numeric NOT NULL, "fee_basis" numeric NOT NULL, "treasury_fee_basis_points" numeric NOT NULL, "insurance_fee_basis_points" numeric NOT NULL, "operators_fee_basis_points" numeric NOT NULL, "total_fee" numeric NOT NULL, "insurance_fee" numeric NOT NULL, "operators_fee" numeric NOT NULL, "treasury_fee" numeric NOT NULL, "dust" numeric NOT NULL, "shares2mint" numeric NOT NULL, "shares_to_treasury" numeric NOT NULL, "shares_to_insurance_fund" numeric NOT NULL, "shares_to_operators" numeric NOT NULL, "dust_shares_to_treasury" numeric NOT NULL, "total_pooled_ether_before" numeric NOT NULL, "total_pooled_ether_after" numeric NOT NULL, "total_shares_before" numeric NOT NULL, "total_shares_after" numeric NOT NULL, "time_elapsed" numeric NOT NULL, "apr_raw" numeric NOT NULL, "apr_before_fees" numeric NOT NULL, "apr" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "transaction_index" numeric NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_8e026ff512af0364043d0a723b4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "node_operator_fees" ("id" character varying NOT NULL, "total_reward_id" character varying, "address" text NOT NULL, "fee" numeric NOT NULL, CONSTRAINT "PK_dcc17d4ed1f492b3d6de3468c87" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c8c3716226072d7bae0ffaae0d" ON "node_operator_fees" ("total_reward_id") `)
        await db.query(`CREATE TABLE "totals" ("id" character varying NOT NULL, "total_pooled_ether" numeric NOT NULL, "total_shares" numeric NOT NULL, CONSTRAINT "PK_3480b9650b4eb64138649f2a416" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "stats" ("id" character varying NOT NULL, "unique_holders" numeric NOT NULL, "unique_anytime_holders" numeric NOT NULL, "last_oracle_completed_id" numeric NOT NULL, CONSTRAINT "PK_c76e93dfef28ba9b6942f578ab1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "shares" ("id" character varying NOT NULL, "shares" numeric NOT NULL, CONSTRAINT "PK_b88473409066c43c2ccb1894a82" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "holder" ("id" character varying NOT NULL, "address" text NOT NULL, "has_balance" boolean NOT NULL, CONSTRAINT "PK_8266ed18d931b168de2723ad322" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "current_fees" ("id" character varying NOT NULL, "fee_basis_points" numeric NOT NULL, "treasury_fee_basis_points" numeric NOT NULL, "insurance_fee_basis_points" numeric NOT NULL, "operators_fee_basis_points" numeric NOT NULL, CONSTRAINT "PK_f799aec8c974126fdaf7111f19f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "shares_burn" ("id" character varying NOT NULL, "account" text NOT NULL, "post_rebase_token_amount" numeric NOT NULL, "pre_rebase_token_amount" numeric NOT NULL, "shares_amount" numeric NOT NULL, CONSTRAINT "PK_a52aecdde7aa7b868d27e6e6c03" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "oracle_config" ("id" character varying NOT NULL, "quorum" numeric NOT NULL, "contract_version" numeric NOT NULL, "allowed_beacon_balance_annual_relative_increase" numeric NOT NULL, "allowed_beacon_balance_relative_decrease" numeric NOT NULL, "epochs_per_frame" numeric NOT NULL, "slots_per_epoch" numeric NOT NULL, "seconds_per_slot" numeric NOT NULL, "genesis_time" numeric NOT NULL, "beacon_report_receiver" text NOT NULL, CONSTRAINT "PK_3e373e109867bd8514487869d38" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "oracle_report" ("id" character varying NOT NULL, "hash" text NOT NULL, "items_processed" numeric NOT NULL, "items_count" numeric NOT NULL, "total_reward_id" character varying, CONSTRAINT "PK_05828c08e675f0f5c4baa96493e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_aa5e522ee26acd5c55ca967578" ON "oracle_report" ("total_reward_id") `)
        await db.query(`CREATE TABLE "oracle_completed" ("id" character varying NOT NULL, "epoch_id" numeric NOT NULL, "beacon_balance" numeric NOT NULL, "beacon_validators" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_3544a04100780771e8bcb7ad1ca" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "oracle_member" ("id" character varying NOT NULL, "member" text NOT NULL, "removed" boolean NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_ea4363e36526b96a1a9106a5f10" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "oracle_expected_epoch" ("id" character varying NOT NULL, "epoch_id" numeric NOT NULL, CONSTRAINT "PK_abaf6f8f95f6b6c4e31894444a9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "beacon_report" ("id" character varying NOT NULL, "epoch_id" numeric NOT NULL, "beacon_balance" numeric NOT NULL, "beacon_validators" numeric NOT NULL, "caller" text NOT NULL, CONSTRAINT "PK_3df95161b52ec69e5694e1157ed" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "node_operator" ("id" character varying NOT NULL, "name" text NOT NULL, "reward_address" text NOT NULL, "staking_limit" numeric NOT NULL, "active" boolean NOT NULL, "total_stopped_validators" numeric, "total_keys_trimmed" numeric NOT NULL, "nonce" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_5b204b4f315c0053547bf32607e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "node_operator_signing_key" ("id" character varying NOT NULL, "operator_id" numeric NOT NULL, "pubkey" text NOT NULL, "removed" boolean NOT NULL, "opidfk" character varying, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_0b34025d712f0e565a0d654d011" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2dc7071603aac382bf52abb370" ON "node_operator_signing_key" ("opidfk") `)
        await db.query(`CREATE TABLE "node_operator_keys_op_index" ("id" character varying NOT NULL, "index" numeric NOT NULL, CONSTRAINT "PK_e6cc205c960850f1de21ddb5daf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "voting_config" ("id" character varying NOT NULL, "support_required_pct" numeric NOT NULL, "min_accept_quorum_pct" numeric NOT NULL, "vote_time" numeric NOT NULL, "objection_phase_time" numeric NOT NULL, CONSTRAINT "PK_c1fafd603ee53c0c83a9b5972e0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "vote" ("id" character varying NOT NULL, "voting_id" character varying, "voter" text NOT NULL, "supports" boolean NOT NULL, "stake" numeric NOT NULL, CONSTRAINT "PK_2d5932d46afe39c8176f9d4be72" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9c9329de9d83f5bd4b31d04b7b" ON "vote" ("voting_id") `)
        await db.query(`CREATE TABLE "voting_objection" ("id" character varying NOT NULL, "voting_id" character varying, "voter" text NOT NULL, "stake" numeric NOT NULL, CONSTRAINT "PK_40bde3e12e72377b1e025ea1500" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_549d7aff86c62fabb6dc5ed458" ON "voting_objection" ("voting_id") `)
        await db.query(`CREATE TABLE "voting" ("id" character varying NOT NULL, "index" integer NOT NULL, "creator" text NOT NULL, "metadata" text NOT NULL, "executed" boolean NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_2dff1e5c53fa2cc610bea30476c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "objection" ("id" character varying NOT NULL, "motion_id" character varying NOT NULL, "objector" text NOT NULL, "weight" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_f66a92a8254c445494f6cc3be60" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c913d483a2294e198c2f5ddf62" ON "objection" ("motion_id") `)
        await db.query(`CREATE TABLE "motion" ("id" character varying NOT NULL, "creator" text NOT NULL, "evm_script_factory" text NOT NULL, "duration" numeric, "start_date" numeric NOT NULL, "snapshot_block" numeric NOT NULL, "objections_amount" numeric NOT NULL, "objections_amount_pct" numeric NOT NULL, "objections_threshold" numeric, "evm_script_hash" text NOT NULL, "evm_script_calldata" text NOT NULL, "status" text NOT NULL, "enacted_at" numeric, "canceled_at" numeric, "rejected_at" numeric, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_6b577ebda54089e75b75f98058d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "easy_track_config" ("id" character varying NOT NULL, "evm_script_executor" text NOT NULL, "motion_duration" numeric NOT NULL, "motions_count_limit" numeric NOT NULL, "objections_threshold" numeric NOT NULL, "is_paused" boolean NOT NULL, CONSTRAINT "PK_9b880e33319d7800695911165ce" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "role" ("id" character varying NOT NULL, "role" text NOT NULL, "address" text NOT NULL, "creator" text NOT NULL, "is_active" boolean NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "evm_script_factory" ("id" character varying NOT NULL, "address" text NOT NULL, "permissions" text NOT NULL, "is_active" boolean NOT NULL, CONSTRAINT "PK_29986fe16a404d7f8553bdbff08" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "app_version" ("id" character varying NOT NULL, "major" integer NOT NULL, "minor" integer NOT NULL, "patch" integer NOT NULL, "impl" text NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_f2573b981a7eac664875e7483ac" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdrawal_queue_config" ("id" character varying NOT NULL, "is_bunker_mode" boolean NOT NULL, "bunker_mode_since" numeric NOT NULL, "contract_version" numeric NOT NULL, "is_paused" boolean NOT NULL, "pause_duration" numeric NOT NULL, CONSTRAINT "PK_c513d5207b7a6f36a4a6b680583" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdrawal_claimed" ("id" character varying NOT NULL, "request_id" numeric NOT NULL, "owner" text NOT NULL, "receiver" text NOT NULL, "amount_of_eth" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_4ffc0cbba35bdf83422ccccffd8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdrawal_requested" ("id" character varying NOT NULL, "request_id" numeric NOT NULL, "requestor" text NOT NULL, "owner" text NOT NULL, "amount_of_st_eth" numeric NOT NULL, "amount_of_shares" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_445c01a88cb0bcad7b669f19568" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdrawals_finalized" ("id" character varying NOT NULL, "from" numeric NOT NULL, "to" numeric NOT NULL, "amount_of_eth_locked" numeric NOT NULL, "shares_to_burn" numeric NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "block_time" numeric NOT NULL, "transaction_hash" text NOT NULL, "log_index" numeric NOT NULL, CONSTRAINT "PK_8cecd00712e0bc83c84c976a87e" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "node_operators_shares" ADD CONSTRAINT "FK_d7de92f3dc4d98a1cd3fd1092e8" FOREIGN KEY ("total_reward_id") REFERENCES "total_reward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "node_operator_fees" ADD CONSTRAINT "FK_c8c3716226072d7bae0ffaae0d8" FOREIGN KEY ("total_reward_id") REFERENCES "total_reward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "oracle_report" ADD CONSTRAINT "FK_aa5e522ee26acd5c55ca9675787" FOREIGN KEY ("total_reward_id") REFERENCES "total_reward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "node_operator_signing_key" ADD CONSTRAINT "FK_2dc7071603aac382bf52abb370b" FOREIGN KEY ("opidfk") REFERENCES "node_operator"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vote" ADD CONSTRAINT "FK_9c9329de9d83f5bd4b31d04b7bf" FOREIGN KEY ("voting_id") REFERENCES "voting"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "voting_objection" ADD CONSTRAINT "FK_549d7aff86c62fabb6dc5ed458b" FOREIGN KEY ("voting_id") REFERENCES "voting"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "objection" ADD CONSTRAINT "FK_c913d483a2294e198c2f5ddf62b" FOREIGN KEY ("motion_id") REFERENCES "motion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "lido_config"`)
        await db.query(`DROP TABLE "lido_transfer"`)
        await db.query(`DROP TABLE "lido_approval"`)
        await db.query(`DROP TABLE "lido_submission"`)
        await db.query(`DROP TABLE "node_operators_shares"`)
        await db.query(`DROP INDEX "public"."IDX_d7de92f3dc4d98a1cd3fd1092e"`)
        await db.query(`DROP TABLE "total_reward"`)
        await db.query(`DROP TABLE "node_operator_fees"`)
        await db.query(`DROP INDEX "public"."IDX_c8c3716226072d7bae0ffaae0d"`)
        await db.query(`DROP TABLE "totals"`)
        await db.query(`DROP TABLE "stats"`)
        await db.query(`DROP TABLE "shares"`)
        await db.query(`DROP TABLE "holder"`)
        await db.query(`DROP TABLE "current_fees"`)
        await db.query(`DROP TABLE "shares_burn"`)
        await db.query(`DROP TABLE "oracle_config"`)
        await db.query(`DROP TABLE "oracle_report"`)
        await db.query(`DROP INDEX "public"."IDX_aa5e522ee26acd5c55ca967578"`)
        await db.query(`DROP TABLE "oracle_completed"`)
        await db.query(`DROP TABLE "oracle_member"`)
        await db.query(`DROP TABLE "oracle_expected_epoch"`)
        await db.query(`DROP TABLE "beacon_report"`)
        await db.query(`DROP TABLE "node_operator"`)
        await db.query(`DROP TABLE "node_operator_signing_key"`)
        await db.query(`DROP INDEX "public"."IDX_2dc7071603aac382bf52abb370"`)
        await db.query(`DROP TABLE "node_operator_keys_op_index"`)
        await db.query(`DROP TABLE "voting_config"`)
        await db.query(`DROP TABLE "vote"`)
        await db.query(`DROP INDEX "public"."IDX_9c9329de9d83f5bd4b31d04b7b"`)
        await db.query(`DROP TABLE "voting_objection"`)
        await db.query(`DROP INDEX "public"."IDX_549d7aff86c62fabb6dc5ed458"`)
        await db.query(`DROP TABLE "voting"`)
        await db.query(`DROP TABLE "objection"`)
        await db.query(`DROP INDEX "public"."IDX_c913d483a2294e198c2f5ddf62"`)
        await db.query(`DROP TABLE "motion"`)
        await db.query(`DROP TABLE "easy_track_config"`)
        await db.query(`DROP TABLE "role"`)
        await db.query(`DROP TABLE "evm_script_factory"`)
        await db.query(`DROP TABLE "app_version"`)
        await db.query(`DROP TABLE "withdrawal_queue_config"`)
        await db.query(`DROP TABLE "withdrawal_claimed"`)
        await db.query(`DROP TABLE "withdrawal_requested"`)
        await db.query(`DROP TABLE "withdrawals_finalized"`)
        await db.query(`ALTER TABLE "node_operators_shares" DROP CONSTRAINT "FK_d7de92f3dc4d98a1cd3fd1092e8"`)
        await db.query(`ALTER TABLE "node_operator_fees" DROP CONSTRAINT "FK_c8c3716226072d7bae0ffaae0d8"`)
        await db.query(`ALTER TABLE "oracle_report" DROP CONSTRAINT "FK_aa5e522ee26acd5c55ca9675787"`)
        await db.query(`ALTER TABLE "node_operator_signing_key" DROP CONSTRAINT "FK_2dc7071603aac382bf52abb370b"`)
        await db.query(`ALTER TABLE "vote" DROP CONSTRAINT "FK_9c9329de9d83f5bd4b31d04b7bf"`)
        await db.query(`ALTER TABLE "voting_objection" DROP CONSTRAINT "FK_549d7aff86c62fabb6dc5ed458b"`)
        await db.query(`ALTER TABLE "objection" DROP CONSTRAINT "FK_c913d483a2294e198c2f5ddf62b"`)
    }
}
